# Commands
MAKE:=make
MKDIR:=mkdir -p
RMDIR:=rm -rf

# Executables
DEBUG_EXEC:=debugBin
RELEASE_EXEC:=releaseBin

# Build Directory
BUILD:=build

# Build Command (i.e. Used to build project)
BUILD_CMD:="$(MAKE)"