# Commands
MAKE:=make
MKDIR:=mkdir -p
RMDIR:=rm -rf

# Executables
DEBUG_EXEC:=debugBin
RELEASE_EXEC:=releaseBin

# Build Directory
BUILD:=build

# Docker/Podman Specific
DOCKER_HOST:=docker
DOCKER_UID ?= $(shell id -u)
DOCKER_GID ?= $(shell id -g)
DOCKER_IMG_NAME:=$(shell basename `git rev-parse --show-toplevel`)
DOCKER_IMG_VER:=1
DOCKER_IMG_FULL_NAME:=$(DOCKER_IMG_NAME):$(DOCKER_IMG_VER)

DOCKER_WORK_DIR:=/app
DOCKER_VOL:= --mount type=bind,source=.,target=$(DOCKER_WORK_DIR)
DOCKER_USER_ARG:= --user $(DOCKER_UID):$(DOCKER_GID)
DOCKER_ARG:= DOCKER_BUILDKIT=1 --init --rm -it $(DOCKER_VOL) -w $(DOCKER_WORK_DIR)/$(BUILD)

# Build Command (i.e. Used to build project)
BUILD_CMD:="$(MAKE)"