# Commands
MAKE := make
MKDIR := mkdir -p
RMDIR := rm -rf

# Default project name obtained from Git top-level directory
PROJECT_NAME ?= $(shell basename `git rev-parse --show-toplevel`)

# Executables
DEBUG_EXEC := debugBin
RELEASE_EXEC := releaseBin

# Build Directory
BUILD := build

# Build Command (i.e. Used to build project)
# Enclose the command in double quotes to handle spaces and special characters
BUILD_CMD := "$(MAKE)"
